# Site settings
name: shuishangdz
email: shuishangdz@gmail.com
author: LC
url: http://www.baidu.com
resume_site: https://github.com/shuishangdz
github: https://github.com/shuishangdz
baseurl: 
description: Actually, less is more!
meta_description: 学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: more intresting , less intrests.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: shuishangdz
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : shuishangdz
    duoshuo:
        short_name : shuishangdz
    disqus :
        short_name : shuishangdz
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
